name: uolia_app
description: Just an app to view and organize your YouTube educational content without losing the learning thread.

version: 1.0.5+6
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  equatable: ^2.0.5
  firebase_analytics: ^9.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_riverpod: ^1.0.4
  flutterfire_ui: ^0.4.3+7
  freezed_annotation: ^2.1.0
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  responsive_framework: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: UoliaIcons
      fonts:
        - asset: assets/fonts/icons/UoliaIcons.ttf
    - family: UoliaTempIcons
      fonts:
        - asset: assets/fonts/icons/UoliaTempIcons.ttf
    - family: DuyIcons
      fonts:
        - asset: assets/fonts/icons/DuyIcons.ttf
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/logo_lockup_flutter_vertical.png
  color_dark: "#042a49"
  image_dark: assets/images/splash/logo_lockup_flutter_vertical_wht.png
  fullscreen: true