// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8_-YCsY8a3xLVvuFOz_hizFdCoWZLhU',
    appId: '1:855479125608:web:474ed8dbe3e1ae397c5ddd',
    messagingSenderId: '855479125608',
    projectId: 'uolia-app',
    authDomain: 'uolia-app.firebaseapp.com',
    storageBucket: 'uolia-app.appspot.com',
    measurementId: 'G-DTXK5EQRZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeyPffdyitpsnYvI0eLlHFR8vOnCHH2I',
    appId: '1:855479125608:android:2bdb5e2cb49a980c7c5ddd',
    messagingSenderId: '855479125608',
    projectId: 'uolia-app',
    storageBucket: 'uolia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTBh191aqmK-QJmDZhfMVzRjri1_sE0o',
    appId: '1:855479125608:ios:d7f146b5c4e7d25e7c5ddd',
    messagingSenderId: '855479125608',
    projectId: 'uolia-app',
    storageBucket: 'uolia-app.appspot.com',
    androidClientId: '855479125608-splqglu8dv49kdofag30kv82pke78vt2.apps.googleusercontent.com',
    iosClientId: '855479125608-stgbo7nh6mrbtfpbf1t0fflspc9r4o31.apps.googleusercontent.com',
    iosBundleId: 'com.uolia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTBh191aqmK-QJmDZhfMVzRjri1_sE0o',
    appId: '1:855479125608:ios:d7f146b5c4e7d25e7c5ddd',
    messagingSenderId: '855479125608',
    projectId: 'uolia-app',
    storageBucket: 'uolia-app.appspot.com',
    androidClientId: '855479125608-splqglu8dv49kdofag30kv82pke78vt2.apps.googleusercontent.com',
    iosClientId: '855479125608-stgbo7nh6mrbtfpbf1t0fflspc9r4o31.apps.googleusercontent.com',
    iosBundleId: 'com.uolia.app',
  );
}
